# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PHPCS check
on:
    workflow_call:

jobs:
    phpcs:
        name: PHPCS check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Check for composer.json
              id: composer_json_check
              run: |
                  if [ ! -f composer.json ]; then
                    echo "composer.json not found. Skipping Composer install."
                    echo "skip_composer=true" >> $GITHUB_OUTPUT
                  else
                    echo "skip_composer=false" >> $GITHUB_OUTPUT
                  fi

            - name: Check for PHP file changes
              id: check-php-files
              run: |
                  git fetch origin ${{ github.base_ref }}
                  git fetch origin ${{ github.head_ref }}
                  CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- | grep '\.php$' || true)
                  if [ -z "$CHANGED_FILES" ]; then
                      echo "No PHP files changed"
                      echo "changed_files=false" >> "$GITHUB_OUTPUT"
                  else
                      echo "PHP files changed"
                      echo "changed_files=true" >> "$GITHUB_OUTPUT"
                  fi

            - name: Setup PHP
              if: steps.composer_json_check.outputs.skip_composer == 'false' && steps.check-php-files.outputs.changed_files == 'true'
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: 'latest'
                  ini-values: memory_limit=256M'
                  coverage: none
                  tools: cs2pr

            - name: Install Composer dependencies
              if: steps.composer_json_check.outputs.skip_composer == 'false' && steps.check-php-files.outputs.changed_files == 'true'
              uses: 'ramsey/composer-install@v3'
              with:
                  # Bust the cache at least once a month - output format: YYYY-MM.
                  custom-cache-suffix: $(date -u "+%Y-%m")

            - name: Run PHPCS Beautifier
              id: phpcbf
              if: steps.composer_json_check.outputs.skip_composer == 'false' && steps.check-php-files.outputs.changed_files == 'true'
              continue-on-error: true
              run: composer phpcbf

            - name: Run PHPCS checks
              id: phpcs
              if: steps.composer_json_check.outputs.skip_composer == 'false' && steps.check-php-files.outputs.changed_files == 'true'
              run: composer phpcs

            - name: Show PHPCS results in PR
              if: ${{ always() && steps.phpcs.outcome == 'failure' }}
              run: cs2pr ./phpcs-report.xml
