# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Playwright Tests
on:
    workflow_call:
        inputs:
            environment:
                type: string
                description: 'The environment to run the tests in.'
                required: true
            script:
                type: string
                description: 'The npm script to run the tests (prefixed by "npm run ").'
                required: true
            timeout:
                type: number
                description: 'The number of minutes to wait before timing out the job.'
                required: false
                default: 10

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    run-tests:
        timeout-minutes: ${{inputs.timeout}}
        runs-on: ubuntu-latest
        environment: ${{inputs.environment}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Cache npm dependencies
              id: npm-cache
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-

            - name: Cache Playwright browsers
              id: playwright-cache
              uses: actions/cache@v4
              with:
                  path: ~/.cache/ms-playwright
                  key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-playwright-browsers-

            - name: Install dependencies
              run: npm ci
              if: steps.npm-cache.outputs.cache-hit != 'true'

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
              if: steps.playwright-cache.outputs.cache-hit != 'true'

            - name: Set environment variables
              run: |
                  echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
                  echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
                  echo "API_AUTH=${{ secrets.API_AUTH }}" >> $GITHUB_ENV

            - name: Run Playwright tests
              id: playwright-tests
              run: npm run ${{inputs.script}}
              continue-on-error: true

            - name: Upload Playwright report
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report

            - name: Fail if Playwright tests failed
              if: steps.playwright-tests.outcome == 'failure'
              run: exit 1
